services:
  express-app:
    build:
      context: .
      target: production
    container_name: express-app-prod
    ports:
      - "9050:9050"
    environment:
      - NODE_ENV=production
    env_file:
      - path: .env.production
        required: true
    restart: unless-stopped