services:
  backend-prod:
    container_name: backend-prod
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - path: .env.production
        required: true
    restart: unless-stopped