services:
  express-app-dev:
    build:
      context: .
      # only builds upto development stage
      target: development
    container_name: express-app-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9050:9050"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    env_file:
      - path: .env.development
        required: true
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"