export default {
	ACCESS_TOKEN_COOKIE_NAME: process.env.ACCESS_TOKEN_COOKIE_NAME || '',
	REFRESH_TOKEN_COOKIE_NAME: process.env.REFRESH_TOKEN_COOKIE_NAME || '',
	ADMIN_ACCESS_TOKEN_COOKIE_NAME:
		process.env.ADMIN_ACCESS_TOKEN_COOKIE_NAME || '',
	ADMIN_REFRESH_TOKEN_COOKIE_NAME:
		process.env.ADMIN_REFRESH_TOKEN_COOKIE_NAME || '',
}
