on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Type-check
        run: yarn type-check

      - name: Format
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Zip source code
        run: zip -r app.zip . -x '*.git*' 'node_modules/*' '*.log' '.env*'

      - name: Generate timestamp
        id: timestamp
        run: echo "value=$(date +'%d-%m-%Y-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mongoacademy-backend
          environment_name: Mongoacademy-backend-prod
          region: ap-south-1
          version_label: v-${{ github.run_number }}-${{ steps.timestamp.outputs.value }}
          deployment_package: app.zip
